import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css', 
                'resources/css/bootstrap.min.css', 
                'resources/css/font-awesome.min.css', 
                'resources/css/themify-icons.css', 
                'resources/css/magnific-popup.css', 
                'resources/css/style.css', 
                'resources/css/enquiry.css', 
                'resources/css/responsive.css', 
                'resources/css/animate.css', 
                'resources/css/owl.carousel.min.css', 
                'resources/css/line-awesome.min.css', 
                'resources/css/flaticon.css', 
                'resources/css/nice-select.css', 
                'resources/css/animated-slider.css', 
                'resources/css/login.css', 
                'resources/css/slick.css', 
                'resources/js/app.js',
                'resources/js/jquery-2.2.4.min.js',
                'resources/js/imagesloaded.pkgd.min.js',
                'resources/js/main.js',
                'resources/js/home.js',
                'resources/js/search-box.js',
                'resources/js/market-place-userLicense.js',
                'resources/js/pricing-page.js',
                'resources/js/enquiry.js',
                'resources/js/jquery.magnific-popup.js',
                'resources/js/wow.min.js',
                'resources/js/jquery.cssslider.min.js',
                'resources/js/sales-enquiry-form.js',
                'resources/js/products.js',
                'resources/js/login.js',
                'resources/js/contact-us.js',
                'resources/js/features-tab.js',
                'resources/js/documentation.js',
                'resources/js/popper.min.js',
                'resources/js/owl.carousel.min.js',
                'resources/js/waypoints.min.js',
                'resources/js/jquery.counterup.min.js',
                'resources/js/imagesloaded.pkgd.min.js',
                'resources/js/isotope.pkgd.min.js',
                'resources/js/jquery.nice-select.min.js',
                'resources/js/worldmap-libs.js',
                'resources/js/mediaelement.min.js',
                'resources/js/blog-data.js',
                'resources/js/blog.js',
                'resources/js/news.js',
                'resources/js/article-details.js',
                'resources/js/worldmap-topojson.js',
                'resources/js/blog-details.js',
                'resources/js/search-result.js',
                'resources/js/bootstrap.min.js',
                'resources/js/slick.js',
                'resources/js/testimonial-slider.js',
                'resources/js/countries.js',
                'resources/js/search-data.js',
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
